import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Clientlayout from "@/component/Clientlayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Expert Solutions",
   icons: {
    icon: "/fav.svg",
  },
  description: "Generated by Expert Solutions",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Clientlayout>
        {children}

        </Clientlayout>
      </body>
    </html>
  );
}
